# Generated by Django 4.1.3 on 2023-01-04 03:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForestSnapPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_FilePath', models.CharField(max_length=255)),
                ('image_DateTime', models.DateTimeField(help_text="Photo DateTime")),
                ('image_Width', models.CharField(max_length=255)),
                ('image_Height', models.CharField(max_length=255)),
                ('FocalLength', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
