# Generated by Django 4.1.3 on 2023-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestsnapphoto',
            name='image_DateTime',
            field=models.DateTimeField(help_text='Photo DateTime'),
        ),
    ]
