# Generated by Django 4.1.3 on 2023-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapmap', '0003_alter_forestsnapphoto_image_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestsnapphoto',
            name='image_DateTime',
            field=models.CharField(max_length=255),
        ),
    ]
